version: '3.4'

services:
  conversationapp:
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/https/conversationapp.crt
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/app/https/conversationapp.key
    volumes:
      - ./ssl-certs:/app/https:ro